development:
  adapter: postgresql
  encoding: unicode
  database: opine_dev_db
  pool: 5
  username: slimfox
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: opine_test_db
  pool: 5
  username: slimfox
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: opine_prod_db
  pool: 5
  username: slimfox
  password: