# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d4ce7e0841eb82f098f2f4167cd162ce68d5a5ab1d529f4d7ff0efccbbc28fc98d54d7227f8713e02621e1f852b9764110348b5259f07f3d4856c371f0dfc9

test:
  secret_key_base: 8b44643c389b2069f793e4de7f09fe621ad78804bedcada350a0996f2194c1a9f2596daf394fc9a645dd7beb08fe18bb314eb8054a767e652c3cb2ee2e0f9c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
